### ISSUE TITLE
Dell 5590

### ISSUE THREAD

**Issue by kris0725pl** [bmuessig/ParksideWeb#1]
Not working....open and notyhing happen.

Win 11 pro
32GB ram
i5 8gen

**Comment by bmuessig** [comment]
Hi, I can guide you through getting it working.

1. Open Powershell in the folder that you downloaded ParksideWeb to (in explorer hold shift and right-click the empty background in the folder and click Open in Powershell)
2. Type: .\ParksideWeb_11_windows_amd64.exe -e
3. You will now see all serial ports on your system. Pick the one of your multimeter.
4. Type (replacing COM10 with your actual serial port): .\ParksideWeb_11_windows_amd64.exe -p COM10 -o

Let me know if it worked for you.
Cheers, Benedikt

**Comment by kris0725pl** [comment]
not working

**Comment by bmuessig** [comment]
Ok, if you need help, provide me more information. Especially what you tried, what worked and what not and why not.
